import React,{useEffect,useRef,useState} from 'react'
import logo from './metr-assets/gateway-mark.svg'
export function BrandMark(){return <span className="brand-symbol" aria-hidden="true"><img src={logo} alt=""/></span>}
export function BrandHero({overview,privateMode=false}){
 const data=overview?.data,failed=overview?.error,storage=data?.storage
 return <section className="brand-hero"><div className="brand-intro"><span className="metr-eyebrow">MATT’S GATEWAY TO AMERICA</span><h1>Matt’s Gateway<br/>to America.</h1><p>{privateMode?'Your files, services and connections. Together, on your Raspberry Pi.':'A window into the computer running at home. See how it’s doing, or leave a file for Matt.'}</p><div className="metr-actions"><a className="metr-button" href={privateMode?'/admin/files':'/drop/'}>{privateMode?'Open your files':'Send a file'} <span aria-hidden="true">↗</span></a><a className="brand-quiet-link" href="#system-monitor">Live system <span aria-hidden="true">↓</span></a></div>{privateMode&&<div className="brand-connected"><i className={data&&!failed?'online':''}/><span>{failed?'Connection unavailable':data?'Connected to '+data.hostname:'Connecting to your Pi'}</span></div>}</div><div className="brand-feature-stack"><a className="brand-feature brand-feature-paper" href={privateMode?'/admin/files':'/drop/'}><span className="brand-feature-kicker">{privateMode?'FILES & STORAGE':'LEAVE SOMETHING HERE'}</span><h2>{privateMode?(failed?'Storage status unavailable':storage?.healthy?'Room for what matters.':'Your shared space.'):'A small, private delivery.'}</h2><p>{privateMode?(storage?.healthy?(storage.free/1099511627776).toFixed(1)+' TiB available on your NAS':'Checking your storage.'): 'One file. Up to 50 MB. Straight to Matt’s inbox.'}</p><span className="brand-card-signature"><BrandMark/></span><span className="brand-card-bottom">{privateMode?'Open storage':'Send a file'} <span aria-hidden="true">↗</span></span></a><a className="brand-feature brand-feature-wave" href={privateMode?'/admin/access':'#private-access'}><span className="brand-feature-kicker">{privateMode?'YOUR PRIVATE CONNECTION':'PUBLIC BY DESIGN'}</span><h2>{privateMode?'A way back home.':'A public view. A private home.'}</h2><p>{privateMode?'Your devices. Your files. Wherever you are.':'Live readings here. Administration and personal files stay private.'}</p><span className="brand-card-bottom">{privateMode?'View your connections':'How access works'} <span aria-hidden="true">↗</span></span></a></div></section>
}
export function PublicNavigation(){
 const [open,setOpen]=useState(false),[compact,setCompact]=useState(false),toggle=useRef(null),menu=useRef(null)
 useEffect(()=>{const scroll=()=>setCompact(window.scrollY>=90);window.addEventListener('scroll',scroll,{passive:true});return()=>window.removeEventListener('scroll',scroll)},[])
 useEffect(()=>{if(!open)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';menu.current?.querySelector('a')?.focus();const key=e=>{if(e.key==='Escape'){setOpen(false);toggle.current?.focus()}if(e.key==='Tab'){const links=[toggle.current,...menu.current.querySelectorAll('a')];const index=links.indexOf(document.activeElement);if(e.shiftKey&&index<=0){e.preventDefault();links[links.length-1].focus()}else if(!e.shiftKey&&index===links.length-1){e.preventDefault();links[0].focus()}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=previous;document.removeEventListener('keydown',key)}},[open])
 const links=[['#system-monitor','Live system'],['/drop/','Send a file'],['#private-access','Private access']]
 return <><header className={'metr-header brand-header'+(compact?' compact':'')+(open?' menu-open':'')}><div className="metr-container metr-header-inner"><a href="/" className="metr-brand" aria-label="Matt’s Gateway to America home"><BrandMark/></a><nav aria-label="Main navigation" className="metr-desktop-nav">{links.map(([href,label])=><a key={href} href={href}>{label}</a>)}<span className="brand-access-badge"><i/>Public view</span></nav><button className="metr-menu-toggle" ref={toggle} aria-label={open?'Close menu':'Open menu'} aria-expanded={open} aria-controls="public-navigation" onClick={()=>setOpen(v=>!v)}>{open?'Close':'Menu'} <span aria-hidden="true">{open?'×':'+'}</span></button></div></header>{open&&<nav id="public-navigation" ref={menu} className="metr-mobile-menu" aria-label="Mobile navigation">{links.map(([href,label])=><a key={href} href={href} onClick={()=>setOpen(false)}>{label}<span aria-hidden="true">↗</span></a>)}<p>Matt’s Gateway to America. Running at home.</p></nav>}</>
}
export function PublicFooter(){return <footer className="metr-footer brand-footer"><div className="metr-container"><div className="metr-footer-top"><div><a href="/" className="metr-brand" aria-label="Matt’s Gateway to America home"><BrandMark/></a><p>A little corner of the internet,<br/>running on a Raspberry Pi at home.</p><a href="/drop/" className="brand-footer-delivery">Leave a file <span aria-hidden="true">↗</span></a></div><div><h2>Explore</h2><a href="#system-monitor">Live system</a><a href="/drop/">Upload inbox</a><a href="#private-access">Private access</a></div><div><h2>Made personal</h2><p>Public readings.<br/>Private files.<br/>Your own computer.</p></div></div><div className="metr-footer-bottom"><span>Matt’s Gateway to America</span><span>matts.public.computer <span aria-hidden="true">↗</span></span></div></div></footer>}
