import React,{useEffect,useState} from 'react'
import './instruments.css'
import './dock.css'
import AmberInstruments from './AmberInstruments'
import ReceiptToast from './ReceiptToast'
import useBottomDock from './useBottomDock'
import useJokeTokens from './useJokeTokens'
const finite=Number.isFinite,clamp=n=>Math.max(0,Math.min(100,n))
export function networkRate(bits){if(!finite(bits)||bits<0)return {value:'—',unit:'Mb/s'};if(bits>=1e9)return {value:(bits/1e9).toFixed(1),unit:'Gb/s'};if(bits>=1e6)return {value:(bits/1e6).toFixed(1),unit:'Mb/s'};return {value:(bits/1e3).toFixed(1),unit:'kb/s'}}
export function networkByteRate(bits){if(!finite(bits)||bits<0)return {value:'—',unit:'MB/s'};const n=bits/8;if(n>=1e9)return {value:(n/1e9).toFixed(1),unit:'GB/s'};if(n>=1e6)return {value:(n/1e6).toFixed(1),unit:'MB/s'};return {value:(n/1e3).toFixed(1),unit:'kB/s'}}
export default function SystemInstruments({telemetry,overview,error='',overviewError='',publicMode=false}){
 const [now,setNow]=useState(Date.now()/1000)
 useBottomDock()
 const tokens=useJokeTokens(publicMode)
 const [mode,setMode]=useState(publicMode?'tokens':'system'),[held,setHeld]=useState(null)
 const system=!publicMode||mode==='system'
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()/1000),5000);return()=>clearInterval(timer)},[])
 const latest=telemetry?.samples?.slice(-1)[0]||{},stamp=latest.ts,stale=!!(error||telemetry?.stale||(stamp&&now-stamp>180)),live=!!(telemetry?.available&&stamp&&!stale)
 const storage=overview?.storage,storageFresh=!!(overview&&!overviewError&&now-overview.sampled_at<=90),capacity=storageFresh&&storage?.healthy&&storage.total>0?clamp(storage.used/storage.total*100):null
 const rx=networkRate(live?latest.net_rx_bps:null),tx=networkRate(live?latest.net_tx_bps:null)
 const values={tokens,cpu:live?latest.cpu:null,memory:live?latest.memory_percent:null,io:live?latest.disk_busy:null,capacity,temp:live?latest.temp:null,ambient:live?latest.ambient_temp:null,network:networkByteRate(live&&finite(latest.net_rx_bps)&&finite(latest.net_tx_bps)?latest.net_rx_bps+latest.net_tx_bps:null),health:{api:live?true:null,database:live?true:null,cache:live?telemetry?.meta?.health?.cache:null,queue:live?telemetry?.meta?.health?.queue:null}}
 const shown=held||values,shownTokens=shown.tokens
 return <section id="system-monitor" className="system-instruments" aria-label="Live system instruments"><header className="instrument-heading"><div><span className="metr-eyebrow">LIVE FROM THE RASPBERRY PI</span><h2>The engine room.</h2></div><span className={'instrument-freshness '+(live?'live':'')} role="status"><i/>{live?'Live · 30-second samples':stale?'Connection stale · readings paused':'Waiting for telemetry'}</span></header><div className="cockpit-artwork lcd-console"><div className="lcd-layout"><div className="lcd-controls"><div className="lcd-mode-switch" role="group" aria-label="Metric category">{publicMode&&<button aria-pressed={!system} onClick={()=>setMode('tokens')}>Token usage</button>}<button aria-pressed={system} onClick={()=>setMode('system')}>System</button></div><a href="/" className="lcd-home">Matt’s Gateway to America</a></div><AmberInstruments values={shown} system={system} running={!held} onToggle={()=>setHeld(held?null:values)}/><div className="lcd-caption"><span>{held?'HOLD · display frozen':live?'LIVE · 30s telemetry':stale?'OFFLINE · readings unavailable':'Connecting to the Pi'}</span><span>{stamp?'Sampled '+new Date(stamp*1000).toLocaleTimeString():'Waiting for a sample'}</span></div></div><ReceiptToast/></div><div className="instrument-accessible">{!system&&shownTokens?<span role="img" aria-label={'Household throughput: '+shownTokens.tps.toFixed(1)+' tokens per second. Monthly token spend: '+Math.floor(shownTokens.total).toLocaleString('en-US')+' tokens.'}/>: [['CPU',shown.cpu],['MEMORY',shown.memory]].map(([name,value])=><span key={name} role="img" aria-label={name+' utilization: '+(finite(value)?value.toFixed(1)+' percent':'unavailable')}/>)}<span role="img" aria-label={'NAS disk busy: '+(finite(values.io)?values.io.toFixed(1)+' percent':'unavailable')}/><span role="img" aria-label={'Network in: '+rx.value+' '+rx.unit}/><span role="img" aria-label={'Network out: '+tx.value+' '+tx.unit}/><span>{finite(capacity)?Math.round(capacity)+'% FULL':'UNAVAILABLE'}</span><span>{finite(values.temp)?values.temp.toFixed(1)+' °C':'CPU temperature unavailable'}</span></div><div className="instrument-caption"><span>{stamp?'Sampled '+new Date(stamp*1000).toLocaleTimeString():'Awaiting a sample'} · {telemetry?.meta?.io_sources?.network||'Network pending'}</span><span>↓ {rx.value} {rx.unit} · ↑ {tx.value} {tx.unit}</span></div><details className="instrument-key"><summary>About these readings <span>↗</span></summary><p>Network traffic combines incoming and outgoing bytes per second. Disk I/O shows the busiest NAS drive. Capacity refers to the NAS array.</p><p>API and database lights reflect fresh dashboard and telemetry responses. Ambient temperature, cache and queue indicators stay unlit when their measurements are not reported. They are not inferred from CPU temperature.</p></details>{stale&&<p className="instrument-warning">Live readings paused. Last recorded values remain in the history below.</p>}</section>
}
