import {gatewayTools,temperatureResult,deliverFile,registerGatewayTools} from '../src/pi/gatewayTools'
const adapter=()=>({temperature:jest.fn(async()=>({available:true,celsius:44})),upload:jest.fn(async()=>({status:'delivered'})),selectedFile:jest.fn(()=>new File(['test'],'test.txt')),subscribe:jest.fn(()=>({subscription:'temperature'})),unsubscribe:jest.fn(()=>({status:'stopped'}))})
test('five explicit tools use fixed operations, mutation annotations and no prompts',async()=>{
 const a=adapter(),tools=gatewayTools(a)
 expect(tools.map(t=>t.name)).toEqual(['get_system_temperature','upload_file','send_matt_a_love_letter','subscribe_system_temperature','unsubscribe_system_temperature'])
 expect(tools[0].annotations.readOnlyHint).toBe(true);expect(tools[2].annotations.consequentialHint).toBe(true)
 await tools[0].execute({});await tools[1].execute({});await tools[3].execute({});await tools[4].execute({})
 expect(a.temperature).toHaveBeenCalled();expect(a.upload).toHaveBeenCalled();expect(a.subscribe).toHaveBeenCalled();expect(a.unsubscribe).toHaveBeenCalled()
})
test('upload tools reject paths and unbounded or empty messages',async()=>{
 const a=adapter(),tools=gatewayTools(a)
 await expect(tools[1].execute({file_name:'../../secret',text_content:'x'})).rejects.toThrow('plain file name')
 await expect(tools[1].execute({text_content:'x'.repeat(64001)})).rejects.toThrow('64,000')
 await expect(tools[2].execute({message:''})).rejects.toThrow()
 expect(a.upload).not.toHaveBeenCalled()
 await tools[2].execute({message:'Dear Matt, hello.'});expect(a.upload.mock.calls[0][0].name).toBe('love-letter.txt')
})
test('Anubis HTML never becomes a false upload success and quotas cannot be bypassed',async()=>{
 const file=new File(['test'],'test.txt')
 const html=jest.fn(async()=>({headers:new Headers({'content-type':'text/html'})}))
 expect((await deliverFile(file,{fetcher:html})).status).toBe('browser_verification_required')
 expect(html.mock.calls[0][0]).toBe('/drop/upload')
 await expect(deliverFile({size:50000001},{fetcher:html})).rejects.toThrow('50 MB')
 const failure=async()=>({status:429,headers:new Headers({'content-type':'application/json'}),json:async()=>({error:'Rate limited'})})
 await expect(deliverFile(file,{fetcher:failure})).rejects.toThrow('Rate limited')
 const accepted=async()=>({status:201,headers:new Headers({'content-type':'application/json'}),json:async()=>({receipt:'a'.repeat(32),bytes:4})})
 expect(await deliverFile(file,{fetcher:accepted})).toEqual({status:'delivered',receipt:'a'.repeat(32),bytes:4})
})
test('temperature tools never substitute fake gauges for missing/stale measurements',()=>{
 expect(temperatureResult({available:true,samples:[{ts:900,temp:45}]},1000).celsius).toBe(45)
 expect(temperatureResult({available:true,samples:[{ts:700,temp:45}]},1000).available).toBe(false)
 expect(temperatureResult({available:true,samples:[{ts:900}]},1000).available).toBe(false)
})
test('tool registration and disable clean up every registered tool',async()=>{
 const context={registerTool:jest.fn(),unregisterTool:jest.fn()},controller=new AbortController()
 expect(await registerGatewayTools(context,gatewayTools(adapter()),controller.signal)).toBe(true)
 expect(context.registerTool).toHaveBeenCalledTimes(5)
 controller.abort();expect(context.unregisterTool).toHaveBeenCalledTimes(5)
 expect(await registerGatewayTools(undefined,[],new AbortController().signal)).toBe(false)
})
